config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "ideas#index"
  resources :ideas
  get 'about' => 'static_pages#about'
  get 'random' => 'static_pages#random'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/idea.rb
class Idea < ApplicationRecord
    validates :description, :author, presence: true
    validates :description, length: { minimum: 500 }, allow_blank: true
    validates :author, length: { maximum: 20 }, allow_blank: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
    def index
        @ideas = Idea.order("created_at DESC").paginate(:page => params[:page], :per_page => 3)
    end

    def create
        @idea = Idea.create(idea_params)
        if @idea.valid?
            flash[:success] = "Your idea has been posted!"
        else
            flash[:alert] = @idea.errors.full_messages.to_sentence
        end
            redirect_to root_path
    end
    
    def edit
        @idea = Idea.find(params[:id])
    end

    def update
        @idea = Idea.find(params[:id])
        if @idea.update(idea_params)
            flash[:success] = "The idea has been updated!"
            redirect_to root_path
        else
            flash[:alert] = @idea.errors.full_messages.to_sentence
            redirect_to edit_idea_path(params[:id])
        end
    end

    def destroy
        @idea = Idea.find(params[:id])
        @idea.destroy
        flash[:success] = "The idea was successfully deleted!"
        redirect_to root_path
      end

    def show
    end
        
      private
    
      def idea_params
        params.require(:idea).permit(:description, :author)
      end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
    def about
    end

    def random
        @idea = Idea.order("RAND()").first
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/ideas/edit.html.erb
<h1>Revise Idea</h1>
<%= simple_form_for @idea, method: :patch do |f| %>
<%= f.input :description %>
<%= f.input :author %>
<%= f.submit 'Submit', class: 'btn btn-primary' %>
<% end %>

app/views/ideas/index.html.erb
<br>
<!-- Button trigger modal -->
<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
  Add Idea
</button>
<br>
<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">Add Idea</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>

      <%= simple_form_for Idea.new do |f| %>
      <div class="modal-body">
          <%= f.input :description %>
          <%= f.input :author %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <%= f.submit 'Submit', class: 'btn btn-primary' %>
      </div>
      <%end%>
    </div>
  </div>
</div>

<% @ideas.each do |idea| %>
<br>
  <div class="card">
    <div class="card-body">
      <blockquote class="blockquote mb-0">
        <p><%= idea.description %></p>
        <footer class="blockquote-footer">by <%= idea.author %></footer>
      </blockquote>
      <br>
      <%= link_to 'Delete', idea_path(idea), class: 'btn btn-sm btn-danger', data: {"turbo-confirm": "Are you sure?","turbo-method": :delete} %>
      <%= link_to 'Revise', edit_idea_path(idea), class: 'btn btn-sm btn-success' %>
    </div>
  </div>
<% end %>

<div class="d-flex justify-content-center will_pagination">
  <%= will_paginate @ideas %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ideator</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <link rel="preconnect" href="https://fonts.googleapis.coht@0,300;0,500;1,300&family=Roboto:wght@100&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Dosis:wght@300;400;600;700&family=Open+Sans:wght@300;400;600;700&family=Pacifico&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <meta charset ="UTF-8">
  </head>

  <body>
  <div id="wrap">
    <%= render 'shared/nav' %>

      <div class = "container">
      <div class = "row">
      <div class = "col-xs-12 col-md-6 col-md-offset-3">
        <%= render 'shared/flash_messages' %>
      <%= yield %>
      </div>
    </div>
    </div>

  </div><!-- wrap -->

  <div class= "footer text-center">
  <%= render partial: 'shared/footer' %>
  
  </body>
</html>

app/views/shared/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <% if message_type == "notice" %>
    <p class="alert alert-info alert-dismissible fade show text-center">
      <%= message %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </p>
  <% elsif message_type == "alert" %>
    <p class="alert alert-danger alert-dismissible fade show text-center">
      <%= message %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </p>
  <% else %>
    <p class="alert alert-<%= message_type %> alert-dismissible fade show text-center">
      <%= message %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </p>
  <% end %>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer text-center">
    <p>&copy; RIYA <%= Date.today.year %> All Rights Reserved</p>
  </div>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Ideator</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="/">All Ideas</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/random">Random Idea</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/about">About</a>
              
              </li>
            </ul>
          </div>
        </div>
      </nav>

app/views/static_pages/about.html.erb
<h1>About Me</h1>

<p> I am Riya Shrestha. I am from Ktm. Currently studying at last year in kantipur City College, Putalisadak </p>

app/views/static_pages/random.html.erb
<br>
<% if @idea.present? %>
  <%= link_to 'Random', random_path, class: 'btn btn-primary btn-block' %>

<div class="card">
    <div class="card-body">
      <blockquote class="blockquote mb-0">
        <p><%= @idea.description %></p>
        <footer class="blockquote-footer">by <%= @idea.author %></footer>
      </blockquote>
      <br>
      <div class="btn-group" role="group">
        <%= link_to 'Delete', idea_path(@idea), class: 'btn btn-sm btn-danger', data: {"turbo-confirm": "Are you sure?", "turbo-method": :delete} %>
        <%= link_to 'Revise', edit_idea_path(@idea), class: 'btn btn-sm btn-success' %>
      </div>
    </div>
  </div>
  <% end %>